---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(GGally)
library(tidyselect)
library(janitor)
library(modelr)
library(pROC)
library(caret)
library(glmulti)
```

```{r}
juice <- read_csv("data/orange_juice.csv")
juice_clean <- clean_names(juice)
juice_trim <- juice_clean %>% 
  select(-c(sale_price_mm, sale_price_ch, price_diff, list_price_diff, store7)) %>% 
  mutate(purchase = as.logical(if_else(purchase == "MM", 1, 0)),
         special_ch = as.logical(special_ch),
         special_mm = as.logical(special_mm),
         store = as.factor(store),
         store_id = as.factor(store_id),
         weekof_purchase = as.factor(weekof_purchase)) %>% 
  rename(purchase_mm = purchase)

sets <- splitstackshape::stratified(juice_trim, c("purchase_mm"), 0.8, bothSets = TRUE)

test_set <- sets$SAMP2
train_set <- sets$SAMP1
```

```{r warning=FALSE, message=FALSE}
glmulti_search_all_mains <- glmulti(
  purchase_mm ~ ., 
  data = train_set,
  level = 1,               # No interactions considered, main effects only
  method = "h",            # Exhaustive approach
  crit = "bic",            # BIC as criteria
  confsetsize = 10,        # Keep 10 best models
  plotty = F, 
  report = T,              # No plots, but provide interim reports
  fitfunction = "glm",     # glm function
  family = binomial(link = "logit")) # binomial family for logistic regression
```

glmulti is liking purchase_mm~1+disc_mm+loyal_ch+pct_disc_ch

```{r}
glmulti_search_previous_mains_one_pair <- glmulti(
  purchase_mm ~ disc_mm + loyal_ch + pct_disc_ch, 
  data = train_set,
  level = 2,               # Interactions considered
  method = "h",            # Exhaustive approach
  crit = "bic",            # BIC as criteria
  confsetsize = 10,        # Keep 10 best models
  marginality = TRUE,      # consider pairs only if both main effects in model
  minsize = 6,             # minsize, maxsize and marginality here force 
  maxsize = 6,             # inclusion of a single pair beyond the five main effects
  plotty = F, 
  report = T,              # No plots, but provide interim reports
  fitfunction = "glm",     # glm function
  family = binomial(link = "logit")) # binomial family for logistic regression

summary(glmulti_search_previous_mains_one_pair)
```

pct_disc_ch:disc_mm + pct_disc_ch:loyal_ch for best interactions

